# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'nodejs-alpine:$(build.buildId)'
  working_dir: 'web-site'

steps:
- script: 
    cd $(working_dir) &&
    docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
