version: '3'
services:
  web:
    image: leead/nodejs-alpine
    build: ./web-site
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./web-site:/usr/scr/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"

    